# Generated by Django 5.1.7 on 2025-04-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='size_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total farm size in hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='stocking_rate',
            field=models.IntegerField(blank=True, help_text='Number of plants per hectare', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='plant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='core.planttype'),
        ),
    ]
