# Generated by Django 5.1.7 on 2025-04-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plantpart_pest_surveillancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('climate_zone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='distribution_pattern',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('clustered', 'Clustered'), ('random', 'Random')], default='uniform', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location_description',
            field=models.CharField(blank=True, help_text='e.g., "Near Katherine River", "Smith Property via XYZ Road"', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='core.region'),
        ),
    ]
