# Generated by Django 5.1.7 on 2025-04-27 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_region_farm_distribution_pattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('season', models.CharField(choices=[('Wet', 'Wet Season'), ('Dry', 'Dry Season'), ('Flowering', 'Flowering Period')], max_length=20)),
                ('confidence_level', models.IntegerField(choices=[(90, '90%'), (95, '95%'), (99, '99%')])),
                ('population_size', models.IntegerField(help_text='Total number of plants in the farm')),
                ('prevalence_percent', models.DecimalField(decimal_places=2, help_text='Assumed pest prevalence percentage', max_digits=5)),
                ('margin_of_error', models.DecimalField(decimal_places=2, default=5.0, help_text='Margin of error percentage', max_digits=5)),
                ('required_plants', models.IntegerField(help_text='Number of plants that should be surveyed')),
                ('percentage_of_total', models.DecimalField(decimal_places=2, help_text='Percentage of total plants to survey', max_digits=5)),
                ('survey_frequency', models.IntegerField(blank=True, help_text='Recommended survey frequency (1 in X plants)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current calculation for this farm')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.farm')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
